contact_links:
  - name: 📜 官方文档 | GO Ldap Admin Doc
    url: http://demo.com
    about: 关于项目的功能用法以及设计考量，都会在官网进行呈现，提交问题之前，请先阅读官方文档，如果还不能满足，则再提问题。
  - name: 👀 Github论坛 | GitHub Discussions
    url: https://github.com/ileostar/contributors
    about: 如果您的问题不是功能或者错误，请转到讨论面板并在提交之前检索您的问题是否已经存在。
  - name: 🙌 贡献指南 | Contribution Guide
    url: https://github.com/ileostar/contribute
    about: 请在提贡献PR前阅读该指南，欢迎提PR
